USE mysql_test;
DELIMITER $$
CREATE PROCEDURE sp_sumofrow(OUT ROWS2 INT)
BEGIN
DECLARE cid INT;
DECLARE FOUND BOOLEAN DEFAULT TRUE;
DECLARE cur_cid CURSOR FOR
SELECT cust_id FROM customers;
DECLARE CONTINUE HANDLER FOR NOT FOUND
SET FOUND=FALSE;
SET ROWS2=0;
OPEN cur_cid;
FETCH cur_cid INTO cid;
WHILE FOUND DO
SET ROWS2=ROWS2+1;
FETCH cur_cid INTO cid;
END WHILE;
CLOSE cur_cid;
END$$
DELIMITER ;
CALL sp_sumofrow(@rows2);